In [13]:
import cv2 
import numpy as np 
  
# Turn on Laptop's webcam
cap = cv2.VideoCapture(0)
  
  
while True:
          
    ret, frame = cap.read()
   
    cv2.circle(frame, (219, 172), 5, (255,255,255), -1)
    cv2.circle(frame, (404, 172), 5, (255,255,255), -1)
    cv2.circle(frame, (534, 478), 5, (255,255,255), -1)
    cv2.circle(frame, (83, 478), 5, (255,255,255), -1)
    
    cv2.line(frame, (219, 172), (83, 478), (0, 0, 255), 3)
    cv2.line(frame, (404, 172), (534, 478), (0, 0, 255), 3)
    
    pts1 = np.float32([[83, 478], [534, 478], [219, 172], [404, 172]])
    #pts2 = np.float32([[0,0],[0,308],[450,308],[450,308]])
    pts2 = np.float32([[83, 478], [534, 478], [83,0], [534,0]])
      
    M = cv2.getPerspectiveTransform(pts1,pts2)
    
    print(M)
    
    dst = cv2.warpPerspective(frame,M,(600,500))

    cv2.imshow('frame', frame) # Inital Capture
    cv2.imshow('frame1', dst) # Transformed Capture
  
    if cv2.waitKey(24) == 27:
        break
  
cap.release()
cv2.destroyAllWindows()

[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.9854

[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.9854

[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.9854

[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.9854

[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
[[ 1.27100755e+01  7.68226193e+00 -3.67212120e+03]
 [-3.40634720e-15  1.98543010e+01 -3.41493977e+03]
 [-1.24155043e-17  2.44980659e-02  1.00000000e+00]]
